### ISSUE TITLE
Avocado Status Server not compatible with python 3.6

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#4359]
The [server](https://docs.python.org/3.6/library/asyncio-eventloop.html#asyncio.Server) python 3.6 has no function `serve_forever()` 

Because of this the avocado status server not working on python 3.6

problem in [server.py](https://github.com/avocado-framework/avocado/blob/master/avocado/core/status/server.py#L41)

**Comment by beraldoleal** [comment]
@richtja I had the error message today. I'm still investigating but seems to me that the problem is with my code. I tried with master and it works.

Can you please, double-check if on master your case is working?

**Comment by richtja** [comment]
@beraldoleal Thanks that you are looking at this. I still have a problem on master. I did some investigation and I think that the problem is that `asyncio.start_server()` creates [asyncio.Server](https://docs.python.org/3.6/library/asyncio-eventloop.html#asyncio.Server) which don't have method `serve_forever()` on python3.6

I am getting this error:

> Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /home/jarichte/Avocado/avocado/avocado/core/status/server.py:38> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/home/jarichte/Avocado/avocado/avocado/core/status/server.py", line 41, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
2020-12-14 15:37:24,304 base_events      L1285 ERROR| Task exception was never retrieved
future: <Task finished coro=<Runner._update_status() done, defined at /home/jarichte/Avocado/avocado/avocado/plugins/runner_nrunner.py:200> exception=AttributeError("'NoneType' object has no attribute 'upper'",)>
Traceback (most recent call last):
  File "/home/jarichte/Avocado/avocado/avocado/plugins/runner_nrunner.py", line 223, in _update_status
    test_state = {'status': last_task_status.get('result').upper()}
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by beraldoleal** [comment]
Looks like is not an error on status server itself.

**Comment by beraldoleal** [comment]
```
 AttributeError: 'NoneType' object has no attribute 'upper'
```

And because of that, for some reason, we have a problem with status_server.

**Comment by richtja** [comment]
Actually I think is opposite, we have this error because of some problem in status_server. This happens when nrunner reads data from status server and it has none.

**Comment by beraldoleal** [comment]
@richtja Looks like you are right about this not being implemented on python 3.6. Maybe we have some skips on tests to skip those when in 3.6, not sure.

So if Travis will be happy with this change, I'm ok.

Now, regarding the `AttributeError`, IMO the line is wrong because is assuming that None it is never returned. And we could refactor there.
